### ISSUE TITLE
Version in HACS is a littlebit curious

### ISSUE THREAD

**Issue by northpower25** [osks/hass-gardena-smart-system#13]
![6D5F2E57-F49D-4623-A46A-A97AF1A773BA](https://user-images.githubusercontent.com/36472486/83140735-d4bc6b00-a0ee-11ea-8862-813120f6aaa9.jpeg)

**Comment by osks** [comment]
Do you mean `f1d5810` and `aba76b0`? Those are git commit hashes. There are no incremental version numbers (not sure how/if that's possible with HACS).

**Comment by Jpsy** [comment]
Just a wild guess:
Did you tag your master commits with version numbers in Git?  Tagging is the standard method to define and communicate a version number in Git. And I bet HACS reads and displays those Git tags. And if they are missing it displays the first chars of the commit hash instead.

**Comment by northpower25** [comment]
I think the problem is that you per now change the master and not create different releases for changes

Example from an other Integration (Alexa Media Player https://github.com/custom-components/alexa_media_player)
![EA785C5A-8B5C-468C-A09E-570F15A67DFC](https://user-images.githubusercontent.com/36472486/83329029-52b37a00-a287-11ea-9b15-36b8daee87ec.jpeg)
![83E493F8-82CF-4620-9895-CC9BEDAD04B8](https://user-images.githubusercontent.com/36472486/83329031-53e4a700-a287-11ea-9933-f5221ed93ea5.jpeg)

**Comment by Jpsy** [comment]
This is a typical case of RTFM. :P  
And @northpower25 it's right:

HACS version numbers are based on GitHub release numbers. GitHub release numbers in turn are bases of tags. But the HACS documentation clearly states that you need full releases, not only tags:

> ### Versions
> If the repository uses GitHub releases, the tagname from the latest release is used to set the remote version. (**NB: just publishing tags is not enough, you need to publish releases)
> If the repository does not use those, the 7 first characters of the last commit will be used.

https://hacs.xyz/docs/publish/start#versions

**Comment by osks** [comment]
I hadn't gotten as far as looking into creating releases for HACS, but that makes sense to start doing.

**Comment by osks** [comment]
Please continue in the new repository: py-smart-gardena/hass-gardena-smart-system#3
