### ISSUE TITLE
Wrong translation or status „cleaning“

### ISSUE THREAD

**Issue by northpower25** [osks/hass-gardena-smart-system#16]
I think it depends from the  vacuumer python source. I see this not in the translation file
![C1062506-D342-4EBB-A52F-ABAF786BB49C](https://user-images.githubusercontent.com/36472486/83282409-d57dfb80-a1d9-11ea-9c13-65ca7eaf8d1c.jpeg)
„Reinigen“ in english „ cleaning“ but it shut be named „mähen“ or in english „cutting“
![898C98B1-62D6-4AF5-B1C6-FE5D55C1DA09](https://user-images.githubusercontent.com/36472486/83282894-91d7c180-a1da-11ea-8809-f679b4612ab0.jpeg)
„Staubsaugerbefehl“ in english „ vacuum command“ shut be named „Rasenmäherbefehl“ or in English „ Lawn mower command“

**Comment by Jpsy** [comment]
Home Assistant does not yet provide a mower device type. The closest we have is the vacuum integration type.   Thus all mower integrations that you find for HA will be based on the vacuum integration. There is no alternative.  
So we currently have to live with the fact that mowers in HA are a sub-species of vacuums and the terminology in many places is vacuum slang.

**Comment by osks** [comment]
Closing this as there is nothing to do here.

The best would be if Home Assistant had a mower platform so we didn't had to use vacuum. But that is out of scope for this project.
